### ISSUE TITLE
反射调用时报NoSuchMethodException崩溃

### ISSUE THREAD

**Issue by br3ant** [hi-dhl/Binding#17]
Oppo R17
binding:1.0.7
------
Caused by: java.lang.NoSuchMethodException: com.datedu.lib_camera.databinding.ActivityTakeVideoBinding.inflate [class android.view.LayoutInflater]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at com.hi.dhl.binding.e.b(ReflectExt.kt:1)
	at com.hi.dhl.binding.g.a.<init>(ActivityViewBinding.kt:2)
	at com.datedu.camera.ui.TakeVideoActivity.<init>(TakeVideoActivity.kt:2)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3399)

**Comment by hi-dhl** [comment]
请问一下，有没有添加混淆?

**Comment by hi-dhl** [comment]
应该是没有添加混淆，在 `proguard-rules ` 文件中添加以下配置即可解决。

```
-keepclassmembers class ** implements androidx.viewbinding.ViewBinding {
    public static ** bind(***);
    public static ** inflate(***);
}
```

**Comment by br3ant** [comment]
close #17 增加混淆
