### ISSUE TITLE
在Navigation启动的Fragment中使用报错

### ISSUE THREAD

**Issue by hahaha28** [hi-dhl/Binding#22]
使用Navigation启动Fragment报错如下：
```
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.hi.dhl.binding.viewbind.FragmentViewBinding.getValue(FragmentViewBinding.kt:34)
        ......
Caused by: java.lang.ClassCastException: androidx.appcompat.widget.AppCompatImageView cannot be cast to android.widget.TextView
        at fun.inaction.stallx.databinding.FragmentSearchBinding.bind(FragmentSearchBinding.java:78)
        at fun.inaction.stallx.databinding.FragmentSearchBinding.inflate(FragmentSearchBinding.java:68)
        at fun.inaction.stallx.databinding.FragmentSearchBinding.inflate(FragmentSearchBinding.java:58)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.hi.dhl.binding.viewbind.FragmentViewBinding.getValue(FragmentViewBinding.kt:34)
```
报错的代码：
```kotlin
class FragmentViewBinding<T : ViewBinding>(
    classes: Class<T>,
    fragment: Fragment
) : FragmentDelegate<T>(fragment) {
... 省略

bind = layoutInflater.invoke(null, thisRef.layoutInflater) as T

... 省略
```

**Comment by hi-dhl** [comment]
看了一下日志是类型转换错误造成的，如下所示，可以分析一下当前 fragmet ，使用这个 View 的地方

```
java.lang.ClassCastException: androidx.appcompat.widget.AppCompatImageView cannot be cast to android.widget.TextView
```
